### ISSUE TITLE
can't load any channel videos

### ISSUE THREAD

**Issue by 2-www** [prateekmedia/flutube#101]
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type 'Null' is not a subtype of type 'bool' in type cast
#0      _InitialData.getContentContext.<anonymous closure> (package:youtube_explode_dart/src/reverse_engineering/pages/channel_upload_page.dart:76)
#1      IterableExtension.firstWhereOrNull (package:collection/src/iterable_extensions.dart:246)
#2      _InitialData.getContentContext (package:youtube_explode_dart/src/reverse_engineering/pages/channel_upload_page.dart:76)
#3      _InitialData._getUploads (package:youtube_explode_dart/src/reverse_engineering/pages/channel_upload_page.dart:60)
#4      _InitialData.uploads (package:youtube_explode_dart/src/reverse_engineering/pages/channel_upload_page.dart:57)
#5      ChannelUploadPage.uploads (package:youtube_explode_dart/src/reverse_engineering/pages/channel_upload_page.dart)
#6      ChannelClient.getUploadsFromPage (package:youtube_explode_dart/src/channels/channel_client.dart)
<asynchronous suspension>
#7      ChannelScreen.build.loadInitData (package:pstube/screens/channel_screen.dart:66)
<asynchronous suspension>
```

**Comment by prateekmedia** [comment]
Fixed in latest!
